### ISSUE TITLE
CentOS 8 - google-guest-agent.service fails to start

### ISSUE THREAD

**Issue by schoonovernumerics** [GoogleCloudPlatform/guest-agent#32] opened 2020-03-23 19:22 UTC
I'm working with CentOS-8 Images on GCP (projects/centos-cloud/global/images/centos-8-v20200316). When booting with this image, the google-guest-agent.service fails to start and returns the following error :
```
Mar 23 19:02:26 centos-8-base-image-node systemd[1]: google-guest-agent.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Mar 23 19:02:26 centos-8-base-image-node systemd[1]: google-guest-agent.service: Failed with result 'exit-code'.
Mar 23 19:02:26 centos-8-base-image-node systemd[1]: google-guest-agent.service: Service RestartSec=100ms expired, scheduling restart.
Mar 23 19:02:26 centos-8-base-image-node systemd[1]: google-guest-agent.service: Scheduled restart job, restart counter is at 5.
Mar 23 19:02:26 centos-8-base-image-node systemd[1]: Stopped Google Compute Engine Guest Agent.
Mar 23 19:02:26 centos-8-base-image-node systemd[1]: google-guest-agent.service: Start request repeated too quickly.
Mar 23 19:02:26 centos-8-base-image-node systemd[1]: google-guest-agent.service: Failed with result 'exit-code'.
```
For reference, the instance that generated this error is created with Hashicorp's Packer (v1.5.4) and executes a startup script that runs `yum install` on a few packages.

**Comment by hopkiw** [comment] 2020-03-23 19:30
@schoonovernumerics thank you for the bug report!

Can you elaborate a little on the role of packer? Packer is usually used for creating derivative images, but I see you are using an official CentOS 8 image. If I launch that image directly, I'm not able to reproduce the issue you're seeing. Is there any surrounding context to this log? Try providing the full log with `journalctl -u google-guest-agent`

**Comment by jonahbull** [comment] 2020-03-23 19:56
We're also running into this when we attempt to use Packer (v1.4.2) to boot the latest CentOS 8 (`centos-8-v20200316`) or RHEL 8 (`rhel-8-v20200319`) images from `centos-cloud` or `rhel-cloud`. We use `packer` to launch a base image and then provision it using `ansible` and save a new custom GCE image. Here's some additional log context from the serial console:
```
Mar 23 19:50:33 packer-5e7912ee-298c-9371-5813-d71b58f71ca9 GCEMetadataScripts[1358]: 2020/03/23 19:50:33 GCEMetadataScripts: Starting startup scripts (version 20200220.00).
Mar 23 19:50:33 packer-5e7912ee-298c-9371-5813-d71b58f71ca9 GCEMetadataScripts[1358]: 2020/03/23 19:50:33 GCEMetadataScripts: Found startup-script in metadata.
Mar 23 19:50:33 packer-5e7912ee-298c-9371-5813-d71b58f71ca9 GCEMetadataScripts[1358]: 2020/03/23 19:50:33 GCEMetadataScripts: startup-script: Packer startup script starting.
Mar 23 19:50:33 packer-5e7912ee-298c-9371-5813-d71b58f71ca9 systemd-hostnamed[939]: Changed static host name to 'packer-5e7912ee-298c-9371-5813-d71b58f71ca9'
Mar 23 19:50:33 packer-5e7912ee-298c-9371-5813-d71b58f71ca9 NetworkManager[916]: <info>  [1584993033.3598] hostname: hostname changed from "localhost" to "packer-5e7912ee-298c-9371-5813-d71b58f71ca9"
Mar 23 19:50:33 packer-5e7912ee-298c-9371-5813-d71b58f71ca9 NetworkManager[916]: <info>  [1584993033.3603] policy: set-hostname: current hostname was changed outside NetworkManager: 'localhost'
Mar 23 19:50:33 packer-5e7912ee-298c-9371-5813-d71b58f71ca9 NetworkManager[916]: <info>  [1584993033.3750] policy: set-hostname: set hostname to 'packer-5e7912ee-298c-9371-5813-d71b58f71ca9' (from system configuration)
Mar 23 19:50:33 packer-5e7912ee-298c-9371-5813-d71b58f71ca9 systemd-resolved[1321]: Positive Trust Anchors:
Mar 23 19:50:33 packer-5e7912ee-298c-9371-5813-d71b58f71ca9 systemd-resolved[1321]: . IN DS 19036 8 2 49aac11d7b6f6446702e54a1607371607a1a41855200fd2ce1cdde32f24e8fb5
Mar 23 19:50:33 packer-5e7912ee-298c-9371-5813-d71b58f71ca9 systemd-resolved[1321]: . IN DS 20326 8 2 e06d44b80b8f1d39a95c0b0d7c65d08458e880409bbc683457104237c7f8ec8d
Mar 23 19:50:33 packer-5e7912ee-298c-9371-5813-d71b58f71ca9 systemd-resolved[1321]: Negative trust anchors: 10.in-addr.arpa 16.172.in-addr.arpa 17.172.in-addr.arpa 18.172.in-addr.arpa 19.172.in-addr.arpa 20.172.in-addr.arpa 21.172.in-addr.arpa 22.172.in-addr.arpa 23.172.in-addr.arpa 24.172.in-addr.arpa 25.172.in-addr.arpa 26.172.in-addr.arpa 27.172.in-addr.arpa 28.172.in-addr.arpa 29.172.in-addr.arpa 30.172.in-addr.arpa 31.172.in-addr.arpa 168.192.in-addr.arpa d.f.ip6.arpa corp home internal intranet lan local private test
Mar 23 19:50:33 packer-5e7912ee-298c-9371-5813-d71b58f71ca9 systemd-hostnamed[939]: Changed host name to 'packer-5e7912ee-298c-9371-5813-d71b58f71ca9'
Mar 23 19:50:33 packer-5e7912ee-298c-9371-5813-d71b58f71ca9 systemd-resolved[1321]: Using system hostname 'packer-5e7912ee-298c-9371-5813-d71b58f71ca9'.
Mar 23 19:50:33 packer-5e7912ee-298c-9371-5813-d71b58f71ca9 systemd[1]: Started Network Name Resolution.
Mar 23 19:50:33 packer-5e7912ee-298c-9371-5813-d71b58f71ca9 systemd[1]: Reached target Host and Network Name Lookups.
Mar 23 19:50:33 packer-5e7912ee-298c-9371-5813-d71b58f71ca9 dbus-daemon[852]: [system] Successfully activated service 'org.freedesktop.resolve1'
Mar 23 19:50:33 packer-5e7912ee-298c-9371-5813-d71b58f71ca9 systemd-resolved[1321]: request_name_destroy_callback n_ref=1
Mar 23 19:50:33 packer-5e7912ee-298c-9371-5813-d71b58f71ca9 systemd[1]: Stopping System Logging Service...
Mar 23 19:50:33 packer-5e7912ee-298c-9371-5813-d71b58f71ca9 GCEMetadataScripts[1358]: 2020/03/23 19:50:33 GCEMetadataScripts: startup-script: Packer startup script done.
Mar 23 19:50:33 packer-5e7912ee-298c-9371-5813-d71b58f71ca9 kdumpctl[1324]: No kdump initial ramdisk found.
Mar 23 19:50:33 packer-5e7912ee-298c-9371-5813-d71b58f71ca9 kdumpctl[1324]: Rebuilding /boot/initramfs-4.18.0-147.5.1.el8_1.x86_64kdump.img
Mar 23 19:50:33 packer-5e7912ee-298c-9371-5813-d71b58f71ca9 GCEGuestAgent[1351]: 2020-03-23T19:50:33.4602Z GCEGuestAgent Info: Instance ID changed, running first-boot actions
Mar 23 19:50:34 packer-5e7912ee-298c-9371-5813-d71b58f71ca9 systemd[1]: Stopping OpenSSH server daemon...
Mar 23 19:50:34 packer-5e7912ee-298c-9371-5813-d71b58f71ca9 systemd[1]: Stopped OpenSSH server daemon.
Mar 23 19:50:34 packer-5e7912ee-298c-9371-5813-d71b58f71ca9 systemd[1]: Stopped target sshd-keygen.target.
Mar 23 19:50:34 packer-5e7912ee-298c-9371-5813-d71b58f71ca9 systemd[1]: Stopping sshd-keygen.target.
[   18.068268] google_guest_agent[3165]: panic: runtime error: index out of range
Mar 23 19:50:34 packer-5e7912ee-298c-9371-5813-d71b58f71ca9 systemd[1]: Reached target sshd-keygen.target.
Mar 23 19:50:34 packer-5e7912ee-298c-9371-5813-d71b58f71ca9 systemd[1]: Starting OpenSSH server daemon...
Mar 23 19:50:34 packer-5e7912ee-298c-9371-5813-d71b58f71ca9 systemd[1]: Started OpenSSH server daemon.
Mar 23 19:50:34 packer-5e7912ee-298c-9371-5813-d71b58f71ca9 systemd[1]: Stopping Login Service...
Mar 23 19:50:34 packer-5e7912ee-298c-9371-5813-d71b58f71ca9 systemd[1]: Stopped Login Service.
Mar 23 19:50:34 packer-5e7912ee-298c-9371-5813-d71b58f71ca9 systemd[1]: Starting Login Service...
Mar 23 19:50:34 packer-5e7912ee-298c-9371-5813-d71b58f71ca9 google_guest_agent[1351]: 2020/03/23 19:50:34 logging client: rpc error: code = PermissionDenied desc = Request had insufficient authentication scopes.
Mar 23 19:50:34 packer-5e7912ee-298c-9371-5813-d71b58f71ca9 google_metadata_script_runner[1358]: 2020/03/23 19:50:34 logging client: rpc error: code = PermissionDenied desc = Request had insufficient authentication scopes.
Mar 23 19:50:34 packer-5e7912ee-298c-9371-5813-d71b58f71ca9 google_osconfig_agent[1326]: 2020/03/23 19:50:34 logging client: rpc error: code = PermissionDenied desc = Request had insufficient authentication scopes.
Mar 23 19:50:34 packer-5e7912ee-298c-9371-5813-d71b58f71ca9 google_guest_agent[1351]: panic: runtime error: index out of range
Mar 23 19:50:34 packer-5e7912ee-298c-9371-5813-d71b58f71ca9 google_guest_agent[1351]: goroutine 97 [running]:
Mar 23 19:50:34 packer-5e7912ee-298c-9371-5813-d71b58f71ca9 google_guest_agent[1351]: main.removeExpiredKeys(0xc0004b62a0, 0x2, 0x2, 0x0, 0x0, 0x0)
Mar 23 19:50:34 packer-5e7912ee-298c-9371-5813-d71b58f71ca9 google_guest_agent[1351]: #011/usr/src/redhat/BUILD/google-guest-agent-20200220.00/google_guest_agent/non_windows_accounts.go:303 +0x435
Mar 23 19:50:34 packer-5e7912ee-298c-9371-5813-d71b58f71ca9 google_guest_agent[1351]: main.(*accountsMgr).set(0xf08208, 0xa0bd01, 0x5)
Mar 23 19:50:34 packer-5e7912ee-298c-9371-5813-d71b58f71ca9 google_guest_agent[1351]: #011/usr/src/redhat/BUILD/google-guest-agent-20200220.00/google_guest_agent/non_windows_accounts.go:113 +0x1d1
Mar 23 19:50:34 packer-5e7912ee-298c-9371-5813-d71b58f71ca9 google_guest_agent[1351]: main.runUpdate.func1(0xc0004dc1f0, 0xad2ec0, 0xf08208)
Mar 23 19:50:34 packer-5e7912ee-298c-9371-5813-d71b58f71ca9 google_guest_agent[1351]: #011/usr/src/redhat/BUILD/google-guest-agent-20200220.00/google_guest_agent/main.go:116 +0xa0
Mar 23 19:50:34 packer-5e7912ee-298c-9371-5813-d71b58f71ca9 google_guest_agent[1351]: created by main.runUpdate
Mar 23 19:50:34 packer-5e7912ee-298c-9371-5813-d71b58f71ca9 google_guest_agent[1351]: #011/usr/src/redhat/BUILD/google-guest-agent-20200220.00/google_guest_agent/main.go:111 +0x24d
Mar 23 19:50:35 packer-5e7912ee-298c-9371-5813-d71b58f71ca9 systemd[1]: Started Login Service.
Mar 23 19:50:35 packer-5e7912ee-298c-9371-5813-d71b58f71ca9 systemd[1]: Stopping Command Scheduler...
Mar 23 19:50:35 packer-5e7912ee-298c-9371-5813-d71b58f71ca9 systemd[1]: Stopped Command Scheduler.
Mar 23 19:50:35 packer-5e7912ee-298c-9371-5813-d71b58f71ca9 systemd[1]: Started Command Scheduler.
Mar 23 19:50:35 packer-5e7912ee-298c-9371-5813-d71b58f71ca9 GCEGuestAgent[1351]: 2020-03-23T19:50:34.6584Z GCEGuestAgent Info: Created google sudoers file
Mar 23 19:50:35 packer-5e7912ee-298c-9371-5813-d71b58f71ca9 systemd[1]: google-guest-agent.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Mar 23 19:50:35 packer-5e7912ee-298c-9371-5813-d71b58f71ca9 systemd[1]: google-guest-agent.service: Failed with result 'exit-code'.
Mar 23 19:50:35 packer-5e7912ee-298c-9371-5813-d71b58f71ca9 systemd[1]: google-guest-agent.service: Service RestartSec=100ms expired, scheduling restart.
Mar 23 19:50:35 packer-5e7912ee-298c-9371-5813-d71b58f71ca9 systemd[1]: google-guest-agent.service: Scheduled restart job, restart counter is at 1.
```
Let me know if there's anything else that'd be helpful!

**Comment by schoonovernumerics** [comment] 2020-03-23 20:01
I'm using Packer to create a custom image on top of the CentOS-8 image. Ultimately, what happens is that Packer fails to build an image due to SSH authentication issues, and I'm suspecting the reported issue on guest-agent is related. My current builds with CentOS-7 do not exhibit any issue.
```
==> googlecompute: Error waiting for SSH: Packer experienced an authentication error when trying to connect via SSH. This can happen if your username/password are wrong. You may want to double-check your credentials as part of your debugging process. original error: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
```

**Comment by schoonovernumerics** [comment] 2020-03-23 20:13
Here's a more complete log from the serial port of the instance created by Packer
```
Mar 23 20:07:51 centos-8-base-image-node systemd[1]: Started Google Compute Engine Guest Agent.
Mar 23 20:07:51 centos-8-base-image-node GCEGuestAgent[3884]: 2020-03-23T20:07:51.0247Z GCEGuestAgent Info: GCE Agent Started (version 20200220.00)
Mar 23 20:07:51 centos-8-base-image-node google_guest_agent[3884]: panic: runtime error: index out of range
Mar 23 20:07:51 centos-8-base-image-node google_guest_agent[3884]: goroutine 45 [running]:
Mar 23 20:07:51 centos-8-base-image-node google_guest_agent[3884]: main.removeExpiredKeys(0xc0001025e0, 0x2, 0x2, 0x0, 0xa122d2, 0xf)
Mar 23 20:07:51 centos-8-base-image-node google_guest_agent[3884]: #011/usr/src/redhat/BUILD/google-guest-agent-20200220.00/google_guest_agent/non_windows_accounts.go:303 +0x435
Mar 23 20:07:51 centos-8-base-image-node google_guest_agent[3884]: main.(*accountsMgr).set(0xf08208, 0xa0bd01, 0x5)
Mar 23 20:07:51 centos-8-base-image-node google_guest_agent[3884]: #011/usr/src/redhat/BUILD/google-guest-agent-20200220.00/google_guest_agent/non_windows_accounts.go:113 +0x1d1
Mar 23 20:07:51 centos-8-base-image-node google_guest_agent[3884]: main.runUpdate.func1(0xc0000f8240, 0xad2ec0, 0xf08208)
Mar 23 20:07:51 centos-8-base-image-node google_guest_agent[3884]: #011/usr/src/redhat/BUILD/google-guest-agent-20200220.00/google_guest_agent/main.go:116 +0xa0
Mar 23 20:07:51 centos-8-base-image-node google_guest_agent[3884]: created by main.runUpdate
Mar 23 20:07:51 centos-8-base-image-node google_guest_agent[3884]: #011/usr/src/redhat/BUILD/google-guest-agent-20200220.00/google_guest_agent/main.go:111 +0x24d
Mar 23 20:07:51 centos-8-base-image-node systemd[1]: google-guest-agent.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Mar 23 20:07:51 centos-8-base-image-node systemd[1]: google-guest-agent.service: Failed with result 'exit-code'.
Mar 23 20:07:51 centos-8-base-image-node systemd[1]: google-guest-agent.service: Service RestartSec=100ms expired, scheduling restart.
Mar 23 20:07:51 centos-8-base-image-node systemd[1]: google-guest-agent.service: Scheduled restart job, restart counter is at 5.
Mar 23 20:07:51 centos-8-base-image-node systemd[1]: Stopped Google Compute Engine Guest Agent.
Mar 23 20:07:51 centos-8-base-image-node systemd[1]: google-guest-agent.service: Start request repeated too quickly.
Mar 23 20:07:51 centos-8-base-image-node systemd[1]: google-guest-agent.service: Failed with result 'exit-code'.
Mar 23 20:07:51 centos-8-base-image-node systemd[1]: Failed to start Google Compute Engine Guest Agent.
Mar 23 20:08:06 centos-8-base-image-node systemd[1]: Started Crash recovery kernel arming.
```

**Comment by jonahbull** [comment] 2020-03-23 20:14
Oh, forgot to mention, the previous CentOS 8 image (`centos-8-v20200309`) did not exhibit this behavior.

**Comment by hopkiw** [comment] 2020-03-23 23:21
OK it looks like it is a new issue specific to derivative images and SSH key generation on boot. will link any follow-ups to this issue. if you're impacted, you can still use the deprecated image centos-8-v20200309

**Comment by Tfmenard** [comment] 2020-03-24 04:58
This actually looks like a Packer issue.
https://github.com/hashicorp/packer/issues/8924#issuecomment-602873329

This PR https://github.com/hashicorp/packer/pull/6445#issue-198662956
was never merged and packer is still using the deprecated "sshKeys" metadata instead of "ssh-keys"

**Comment by hopkiw** [comment] 2020-03-24 17:23
the deprecated sshKeys metadata should not cause this issue - though i will appreciate if packer fixes that, this seems to have been just a bug in the new guest software :) PR is linked to this issue.

**Closed** 2020-03-24 21:30 UTC
