### ISSUE TITLE
Error getting config status, workload certificates may not be configured since 20230202.00

### ISSUE THREAD

**Issue by rivershah** [GoogleCloudPlatform/guest-agent#200] opened 2023-02-03 11:25 UTC
Since the [release](https://github.com/GoogleCloudPlatform/guest-agent/releases/tag/20230202.00) seeing these errors. Using [terraform](https://registry.terraform.io/modules/digio/gitlab-runner/google/0.0.13?utm_content=documentLink&utm_medium=Visual+Studio+Code&utm_source=terraform-ls) to create `docker+machine` executor for gitlab. Was working flawlessly for months prior to most recent release.

```
Feb  3 11:08:08 gitlab-ci-runner google_metadata_script_runner: startup-script: Installing Docker...
Feb  3 11:10:43 gitlab-ci-runner systemd: Starting GCE Workload Certificate refresh...
Feb  3 11:10:43 gitlab-ci-runner gce_workload_cert_refresh: 2023/02/03 11:10:43: Error getting config status, workload certificates may not be configured: HTTP 404
Feb  3 11:10:43 gitlab-ci-runner gce_workload_cert_refresh: 2023/02/03 11:10:43: Done
Feb  3 11:10:43 gitlab-ci-runner systemd: Started GCE Workload Certificate refresh.
```

**Comment by rally-dimi** [comment] 2023-04-24 11:47
Anyone looking into it ? 
This query is being executed int the GO code & it returns HTTP404:
```
http://169.254.169.254/computeMetadata/v1/instance/workload-certificates-config-status -H "Metadata-Flavor:Google"
```

**Comment by vorakl** [comment] 2023-04-24 22:00
Could you, guys, please share some background with us?
For instance, how this issue affects your workflow, what exactly (in a bigger context) doesn't work. If, as you noticed, this functionality doesn't work for a couple months, what is your workaround?

As you also noticed, the problem is related to the metadata endpoint, that no longer exists. It is not a specific Guest Agent's issue that could be fixed in its code. Guest Agent acts as a client in the interactions with the metadata server.

We'll try to figure out what is wrong, but we need to know how urgent it is, and what exactly it breaks on a customer's side, taking into consideration the amount of time when it doesn't work as expected.

**Comment by rally-dimi** [comment] 2023-05-03 15:35
@vorakl is this feature is optional or it would stop agent from functioning?
Thank you.

**Comment by vorakl** [comment] 2023-05-03 17:10
Guest Agent can definitely work without this feature, no doubts. Guest Agent collects a number of features/functionality, and if one doesn't work as expected, other keep working.

This particular feature is special. It seems, there was a feature request some times ago that got implemented and shipped, but left undocumented. I don't see any mentioning in the documentation about its functionality or purpose. And I didn't find anyone who was aware about details related to the feature. That's why I asked you what exactly this issue breaks in your workflow, why you need this feature, and, if it's really needed, what a workaround you found as it is not working for months in a row.

Although, if you just noticed this error message in the logs and nothing really affects your workflow, meaning, all expected behavior from the documentation works fine, then I don't see any reasons to worry about it.

**Comment by kfsone** [comment] 2023-06-28 00:33
When looking at a potentially certificates related SSL issue, this message naturally attracts your attention. I don't believe it has anything to do with the issue I'm root causing, but since I don't know what it's telling me, I can't know that for sure.

**Comment by derhally** [comment] 2023-10-25 22:21
Our logs are being polluted by these errors.   We are seeing them on ubuntu 22.04 minimal

**Comment by timdrysdale** [comment] 2023-10-27 11:52
same for us (log pollution) with ubuntu-2004-focal-lts

**Comment by oxytis** [comment] 2023-10-31 19:35
thanks... works!

**Comment by ei-grad** [comment] 2023-11-16 15:31
This should be enough:
```
systemctl disable gce-workload-cert-refresh.timer
```

**Comment by ei-grad** [comment] 2023-11-17 09:32
@vorakl it doesn't look like a right thing, to enable by default some timer which fails every 10 minute on all (non-GKE?) machines in Google Cloud, I guess it spams 10th GBs a day in Google Cloud Monitoring overall, not a big deal but what about carbon emission? :-)

Could it be enabled by some startup script only for instances where it is needed?

Or, at least quit silently if there are no credentials to update?

Also, is this timer really needed? Having a similar logic in `google_guest_agent` makes it look like a reasonable question. Related errors in logs from the `google_guest_agent` service:
> Skipping scheduling credential generation job, failed to reach client credentials endpoint(instance/credentials/certs) with error: error connecting to metadata server, status code: 404
> ERROR scheduler.go:177 Failed to schedule job MTLS_MDS_Credential_Boostrapper with error: ShouldEnable() returned false, cannot schedule job MTLS_MDS_Credential_Boostrapper

**Comment by ei-grad** [comment] 2023-11-17 10:09
Oh! It looks like this has been fixed in fresh guest-agent versions.
* 1:20231115.00-g1 (version in current debian bullseye images) is not affected
* 20230426.00-0ubuntu2~22.04.0 (latest available in ubuntu 22.04 repos) - affected

**Comment by olalofgren** [comment] 2024-01-08 15:24
Any ideas when this guest-agent will be upgraded for Ubuntu?

**Comment by foxmadr** [comment] 2024-01-30 10:32
I'm also receiving this error on Ubuntu 20.04 image.

It may not be related but there is also an error on the Load Balancer, the error has status code 502 and statusDetails: "config_not_found". Strange that config is not found. Is not the same error on GCE load balancer machines?

**Comment by ChaitanyaKulkarni28** [comment] 2024-02-07 18:05
Sorry for the late response. I believe this issue is already fixed in Guest Agent and ubuntu will also have an update with this fix soon.

**Closed by ChaitanyaKulkarni28** 2024-02-07 18:05 UTC

**Comment by ei-grad** [comment] 2024-02-08 14:44
Does anybody know a proper way to ping relevant Ubuntu maintainers?
